from __future__ import annotations

import json

from laborlens.research.research_bundle import ResearchBundle

SYSTEM_INSTRUCTIONS = """
You are the writing component of LaborLens, an evidence-first
labor-market research system.

You receive a verified ResearchBundle generated by deterministic
statistical code.

Hard rules:

1. Use only facts contained in the bundle.
2. Never invent statistics, dates, mechanisms, explanations, or causes.
3. Never claim causation from correlation or co-movement.
4. Signal contributions are standardized statistical signals, not raw
   percentage changes.
5. Clearly distinguish observation from interpretation.
6. If the skeptic verdict is not "supported", clearly state the uncertainty.
7. Never call an episode unprecedented unless the bundle proves that.
8. Historical analogs are comparisons, not identical events.
9. Do not introduce external facts.
10. Every numerical statement must come directly from the bundle.
11. Do not infer job losses, layoffs, hiring freezes, recession, policy
    causes, or sector effects unless explicitly present in the bundle.
12. Avoid sensational language.

Write concise economic journalism.

Required structure:

# Headline

## Direct answer

## What changed?

## Evidence

## Historical context

## What this does not establish

## Methodology
""".strip()


def bundle_payload(
    bundle: ResearchBundle,
) -> dict:
    return {
        "episode": {
            "id": bundle.episode_id,
            "start_date": (bundle.episode.start_date.isoformat()),
            "end_date": (bundle.episode.end_date.isoformat()),
            "duration_months": (bundle.duration_months),
        },
        "claim": {
            "headline": (bundle.claim.headline),
            "type": (bundle.claim.claim_type),
            "confidence": (bundle.claim.confidence),
        },
        "statistics": {
            "mean_episode_score": (bundle.mean_episode_score),
            "peak_episode_score": (bundle.peak_episode_score),
            "historical_percentile": (bundle.historical_percentile),
        },
        "skeptic": {
            "verdict": (bundle.skeptic.verdict),
            "score": (bundle.skeptic.score),
            "findings": [
                {
                    "code": finding.code,
                    "severity": finding.severity,
                    "message": finding.message,
                }
                for finding in bundle.skeptic.findings
            ],
        },
        "evidence": {
            "supporting": [
                {
                    "series_id": item.series_id,
                    "contribution": (item.contribution),
                }
                for item in bundle.evidence.supporting
            ],
            "opposing": [
                {
                    "series_id": item.series_id,
                    "contribution": (item.contribution),
                }
                for item in bundle.evidence.opposing
            ],
            "breadth": (bundle.evidence.breadth),
        },
        "historical_analogs": [
            {
                "start_date": (analog.start_date.isoformat()),
                "end_date": (analog.end_date.isoformat()),
                "score": analog.score,
                "confidence": (analog.confidence),
                "duration_months": (analog.duration_months),
            }
            for analog in bundle.historical_analogs
        ],
        "provenance": [
            {
                "series_id": item.series_id,
                "observation_date": (item.observation_date.isoformat()),
                "value": item.value,
                "realtime_start": (item.realtime_start.isoformat()),
                "realtime_end": (item.realtime_end.isoformat()),
            }
            for item in bundle.provenance
        ],
    }


def build_writer_input(
    bundle: ResearchBundle,
) -> str:
    payload = bundle_payload(bundle)

    return "Write an article using only the verified ResearchBundle below.\n\n" + json.dumps(
        payload,
        indent=2,
        sort_keys=True,
    )
