services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: laborlens-clickhouse

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: laborlens
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: laborlens
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8123/ping || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  clickhouse_data:
